<?php
    // This is the action of the form generated by the script
    // add_review_form.php
    // After adding the new review this script should redirect
    // the user to the movie page (movie.php?film=XXXX)
    // In case of bad information (name, organization or review
    // containing only white spaces) this script should redirect
    // the user to an error page (add_review_error.php)
    include("include/movie.inc.php");
    
    $info = array();
    $name = trim($_GET[ 'name' ]);
    $org = trim($_GET['organization']);
    $rating = trim($_GET['rating']);
    $review = trim($_GET['review']);
    $film = $_GET['film'];

    if(empty($name) or empty($org) or empty($rating) or empty($review)){
        header("Location: add_review_error.php?film=" . $film);
        exit();
    }
    
    $review_list = all_review_path(movie_path($film));
    $new_review_path = movie_path($film) . "/review" . count($review_list)+1 . ".txt";

    file_put_contents($new_review_path, $review, FILE_APPEND);
    file_put_contents($new_review_path, "\n".$rating, FILE_APPEND);
    file_put_contents($new_review_path, "\n".$name, FILE_APPEND);
    file_put_contents($new_review_path, "\n".$org, FILE_APPEND);

    header("Location: movie.php?film=" . $film);
    exit();
    
?>
